### ISSUE TITLE
How are edges defined?

### ISSUE THREAD

**Issue by Mapengfeixx** [edw4rdyao/DL_EEG#6]
Hello, thank you very much for your code, but I'm a bit confused， for example:
![Snipaste_2023-09-13_22-44-27](https://github.com/edw4rdyao/DL_EEG/assets/80090568/44bb31a1-0fa8-45b4-a468-e90c215b699e)

How are edges defined?

**Comment by edw4rdyao** [comment]
Very sorry for the late reply
The edges defined based on position like the paper [Adaptive Spatiotemporal Graph Convolutional Networks for Motor Imagery Classification](https://ieeexplore.ieee.org/document/9317747) Fig. 2.

![image](https://github.com/edw4rdyao/DL_EEG/assets/60951682/996e720b-b86f-4a51-ac2e-cd49ea2be86a)

**Comment by Mapengfeixx** [comment]
I understand. Thank you very much for your reply. Wishing you good health and publishing more and more paper.
