### ISSUE TITLE
Consider adding eeg_mi_dl to NITRC

### ISSUE THREAD

**Issue by arnodelorme** [edw4rdyao/DL_EEG#9]
NITRC references all the neuroscience tools. NITRC is a non-profit NIH-sponsored website. This will help increase your tool (and associated paper) visibility.

https://www.nitrc.org/

**Comment by edw4rdyao** [comment]
@arnodelorme Apologies for the late reply. NITRC is a fantastic project, and I'm happy to help. I've recently organized this repository. Could you please provide the specific process for adding this repository to NITRC?😊

**Comment by arnodelorme** [comment]
Sorry I was traveling.

Adding to NITRC is easy, register with your Gmail address and then press the button register new tool, and follow the prompts.
Cheers,

Arno
